artifact_uri: file:///C:\Users\Alina Shrestha\Documents\studybuddy-dk\mlflow_tracking/953456116672442040/9ee6705d3ae24ff0aa5bbe88aa9db4a6/artifacts
end_time: 1776160302604
entry_point_name: ''
experiment_id: '953456116672442040'
lifecycle_stage: active
run_id: 9ee6705d3ae24ff0aa5bbe88aa9db4a6
run_name: pipeline_20260414_095142
source_name: ''
source_type: 4
source_version: ''
start_time: 1776160302372
status: 3
tags: []
user_id: Alina Shrestha
