artifact_location: file:///C:\Users\Alina Shrestha\Documents\studybuddy-dk\mlflow_tracking/953456116672442040
creation_time: 1776114727347
experiment_id: '953456116672442040'
last_update_time: 1776114727347
lifecycle_stage: active
name: studybuddy_dk
trace_location: null
workspace: default
